//! DTD (Document Type Definition): Declarations as data, reading them, and validating documents based on the DTD.
//!
//! XML 1.0 defines DTDs, and specification-compliant processors are required to read DTDs declared within a document,
//! even if they do not perform validation. Entity declarations provide replacement text, while attribute-list
//! declarations provide default values and determine which values are normalized as tokens. Validation based on a
//! DTD is optional and treated as a separate process. This module consists of the following three components:
//!
//! - [`model`]: Declarations as data. [`Dtd`] is constructed via declaration methods and read via query methods. Since
//!   DTDs were formulated before the concept of namespaces was introduced, name matching occurs at the lexical level,
//!   including prefixes.
//! - [`read`]: Parses declarations to generate a [`Dtd`].
//!   - The document parser in [`io::parse`](crate::io::parse) reads the internal and external subsets of the `DOCTYPE`
//!     via [`DtdAssembly`].
//!   - [`DtdReader`] reads a DTD stored in a standalone file.
//!   - [`parse_subset`] reads a subset provided directly. External resources, such as external subsets or external
//!     parameter entities, are retrieved only through a resolver provided by the caller.
//! - [`validate`]: Validates a document based on a DTD using an event-based
//!   [`Validator`](crate::event::validate::Validator).
//!   - [`DtdSchema`] represents a DTD held as a reusable schema.
//!   - [`DocumentDtd`] performs validation based on the DTD declared by the document itself.
//!   - [`DtdValidator`] is a per-document validator generated by either of the above.
//!
//! Types frequently used by the caller are re-exported here.

pub mod model;
pub mod read;
pub mod validate;

pub use model::{
  AttDef, AttType, ContentParticle, ContentSpec, DefaultDecl, Dtd, ExternalId, GeneralEntity, Occurs, ParameterEntity,
};
pub use read::{DtdAssembly, DtdOutcome, DtdReader, ExternalPe, normalize_tokenized, parse_subset};
pub use validate::{DocumentDtd, DtdSchema, DtdValidator};
