//! XML writing involves the exchange between events generated by the application and the byte sequences written out
//! by a handler based on those events.
//!
//! This module provides functionality for converting documents or events into byte streams. [`WriterSource`] converts
//! serialization operations invoked by the application into a sequence of events. Meanwhile, [`XmlWriter`] is a type
//! of [`EventHandler`](crate::event::EventHandler) that writes received events as XML text. Combining these components
//! fulfills a role similar to StAX's `XMLStreamWriter`. Furthermore, by placing a
//! [`StrictXmlValidator`](crate::event::strict::StrictXmlValidator) or other validator upstream of the [`XmlWriter`],
//! it is possible to output validated XML.
//!
//! Since the components interact solely via events, they can be freely combined with other event-handling components.
//! For instance, application calls can be passed to a [`DomBuilder`](crate::dom::build::DomBuilder) to construct a
//! tree, or content obtained by traversing a document (read by a parser) or a tree can be written out directly via
//! [`XmlWriter`] without intermediate processing.
//!
//! However, this module does not perform validation of the document content itself. Issues such as the use of
//! undeclared namespaces, names that do not conform to XML naming rules, or tag mismatches are detected by a
//! [`Validator`](crate::event::validate::Validator). To handle these checks, place a validator before the
//! [`XmlWriter`] within a [`Dispatch`](crate::event::Dispatch) chain. If the validator rejects an event, processing
//! can be halted before the corresponding byte sequence is written.
//!
//! Regarding your specifications, when choices exist, such as whether to use `<a/>` or `<a></a>`, which quotation
//! marks to use for attribute values, or whether to escape every `>` character, the implementation effectively becomes
//! an [`XmlWriter`]-equivalent process.

mod escape;
mod source;
mod writer;

pub use source::WriterSource;
pub use writer::XmlWriter;
