//! Provides a Writer capable of generating XML with schema validation.
//!
//! This crate writes XML two ways. From a tree that already exists, [`Serializer`](crate::Serializer) walks it and
//! writes it. With no tree in hand, [`XmlWriter`] writes event by event, as the caller makes each call. However,
//! neither checks the output XML against a schema.
//!
//! Sometimes the caller needs that check when sending XML over a socket connection; the generated XML may not be
//! reloadable, so the caller might require such checks. When the output must satisfy a contract a downstream reader
//! will enforce, a DTD or another schema, emitting invalid XML and learning of it only when the consumer refuses the
//! document is a poor bargain. The fault is worth catching where it is made.
//!
//! Xenolith already includes a mechanism in which [`Validator`] examines the document's event stream and reports any
//! deviations from the schema, regardless of where the events originate. This behavior is independent of where the
//! events originate — whether they're generated by input parsing or by traversing a constructed tree — the contract
//! for their behavior remains the same.
//!
//! xenolith already has the means. A [`Validator`] checks a stream of document events and reports each departure from
//! the schema, and it is the same contract whether the events come from a parser reading input or a walk over a built
//! tree. It does not care what produces the events.
//!
//! Thus, by passing each write operation's content to a validator before output, we can extend [`XmlWriter`] to
//! prevent outputting content prohibited by the schema. That's what the `validating` module provides: the
//! [`ValidatingWriter`].
//!

use std::io;

use xenolith_core::attr::{AttributeList, AttributeRef, Attributes};
use xenolith_core::chars;
use xenolith_core::error::{Location, Result};
use xenolith_core::name::{NamePool, QName};
use xenolith_validate::{FailFast, Validator, ValidityError};

use crate::XmlWriter;

/// An [`XmlWriter`] that checks each write against a [`Validator`] and refuses structures that the schema forbids.
///
/// It is a separate type from [`XmlWriter`] because it keeps [`XmlWriter`] free of any validation dependency, so a
/// caller that doesn't validate pays nothing at compile time. It also suits different model validation needs: a
/// schema judges a start element by its attributes and name, so this writer buffers the whole element to check it,
/// whereas [`XmlWriter`] simply streams. This writer wraps an [`XmlWriter`] and adds that layer.
///
/// The caller drives it exactly as an [`XmlWriter`]. Any [`Validator`] works here, and
/// [`Schema::validator`](xenolith_validate::Schema::validator) supplies a fresh one for each document.
///
/// # What it guarantees
///
/// Content the schema rejects never reaches the output: each write is checked before the bytes it governs are written,
/// so a refused element or its text leaves nothing behind, and the output holds a valid prefix the caller may keep or
/// discard. Because a start element is checked once its attributes are in, its violation surfaces on the call after
/// the one that opened it. The whole-document checks are the exception: an `IDREF` with no `ID`, or a wrong root, is
/// caught by [`finish`](Self::finish) after those bytes are already out. Once a write is refused, the writer is
/// failed, and every later call returns that same error.
///
/// # What it does not check
///
/// The XML declaration, the document type declaration, comments, and processing instructions pass straight through
/// unvalidated. A name is checked in its lexical form, so a schema matching on a namespace URI is not driven from here,
/// though a DTD, which matches the lexical form, is unaffected. Everything [`XmlWriter`] leaves to the caller stays
/// there, balancing every start with an end included.
///
/// # Examples
///
/// ```
/// use xenolith_parser::dtd::DtdReader;
/// use xenolith_serialize::ValidatingWriter;
/// use xenolith_validate::{DtdSchema, Schema};
///
/// let (dtd, pool) = DtdReader::new("<!ELEMENT note (#PCDATA)>".as_bytes()).read()?;
/// let schema = DtdSchema::new(dtd, pool).with_root("note");
///
/// let mut w = ValidatingWriter::new(Vec::new(), schema.validator());
/// w.write_start_element("note")?;
/// w.write_characters("hi")?;
/// w.write_end_element()?;
/// assert_eq!(String::from_utf8(w.finish()?).unwrap(), "<note>hi</note>");
/// # Ok::<(), xenolith_core::Error>(())
/// ```
///
pub struct ValidatingWriter<W> {
  inner: XmlWriter<W>,
  validator: Box<dyn Validator>,
  /// The names this writer has interned, lent to the validator on every call that carries one.
  pool: NamePool,
  /// The start element collected but not yet checked or emitted, if one is open.
  pending: Option<PendingStart>,
  /// The elements already emitted and not yet ended, outermost first.
  open: Vec<QName>,
  /// The error that refused a write, kept so every later call returns it.
  failure: Option<ValidityError>,
}

/// A start element whose name and attributes are collected but not yet emitted, so the validator can check it whole.
struct PendingStart {
  name: QName,
  /// The name as the caller wrote it, kept because the output has to carry that form and not a rendering of `name`.
  lexical: String,
  attributes: Vec<PendingAttribute>,
}

/// One attribute of a pending start element.
struct PendingAttribute {
  name: QName,
  /// The name as the caller wrote it, for the same reason as in [`PendingStart`].
  lexical: String,
  value: String,
  declares_namespace: bool,
}

/// The attributes of a pending start element, presented as an [`AttributeList`] so the validator can read them.
struct PendingAttributes<'a> {
  attributes: &'a [PendingAttribute],
}

impl AttributeList for PendingAttributes<'_> {
  fn len(&self) -> usize {
    self.attributes.len()
  }

  fn get(&self, index: usize) -> Option<AttributeRef<'_>> {
    let attribute = self.attributes.get(index)?;
    Some(AttributeRef {
      name: attribute.name,
      value: &attribute.value,
      declares_namespace: attribute.declares_namespace,
    })
  }
}

impl<W: io::Write> ValidatingWriter<W> {
  /// Creates a writer over `out` that checks each write against `validator`.
  ///
  /// The validator must be one that has not yet seen a document, since it carries the state of the document it is
  /// checking. [`Schema::validator`](xenolith_validate::Schema::validator) returns a fresh one.
  ///
  pub fn new(out: W, validator: Box<dyn Validator>) -> Self {
    Self {
      inner: XmlWriter::new(out),
      validator,
      pool: NamePool::new(),
      pending: None,
      open: Vec::new(),
      failure: None,
    }
  }

  /// Writes the XML declaration. It is not a validated event, so the validator never sees it.
  ///
  /// It has to come first, before any other content.
  ///
  /// # Errors
  ///
  /// If the writer has already failed, that error. Otherwise an error from the underlying writer.
  ///
  pub fn write_declaration(&mut self, standalone: Option<bool>) -> Result<()> {
    self.guard()?;
    self.inner.write_declaration(standalone)?;
    Ok(())
  }

  /// Writes a document type declaration. It is not a validated event, so the validator never sees it.
  ///
  /// The declaration tells a reader which DTD to check the document against. The schema this writer enforces is a
  /// separate thing, and keeping the two in step is the caller's business.
  ///
  /// It has to come before the root element.
  ///
  /// # Errors
  ///
  /// If the writer has already failed, that error. Otherwise an error from the underlying writer.
  ///
  /// # Panics
  ///
  /// If an element has already reached the output. A document type declaration may not appear inside the document
  /// element.
  ///
  pub fn write_doctype(&mut self, name: &str, public_id: Option<&str>, system_id: Option<&str>) -> Result<()> {
    self.guard()?;
    self.inner.write_doctype(name, public_id, system_id)?;
    Ok(())
  }

  /// Opens an element. Attributes may follow until the first content, the next start element, or the matching end.
  ///
  /// This call flushes the element opened before it, so that element's check, and any violation it holds, falls here
  /// rather than on the call that opened it.
  ///
  /// # Errors
  ///
  /// If the writer has already failed, that error. Otherwise a validity error if the element this call flushes breaks
  /// the schema, or an error from the underlying writer.
  ///
  pub fn write_start_element(&mut self, name: &str) -> Result<()> {
    self.guard()?;
    self.flush_pending()?;
    let qname = self.intern(name);
    self.pending = Some(PendingStart { name: qname, lexical: name.to_owned(), attributes: Vec::new() });
    Ok(())
  }

  /// Adds an attribute to the element just opened.
  ///
  /// The attribute is held with its element and checked together with it, so this call reports no validity error of
  /// its own. That check falls on whichever later call flushes the element.
  ///
  /// # Errors
  ///
  /// If the writer has already failed, that error.
  ///
  /// # Panics
  ///
  /// If no element is open, or if the element already has content.
  ///
  pub fn write_attribute(&mut self, name: &str, value: &str) -> Result<()> {
    self.guard()?;
    let qname = self.intern(name);
    let declares_namespace = name == "xmlns" || name.starts_with("xmlns:");
    let pending = self.pending.as_mut().expect("write_attribute must follow write_start_element");
    pending.attributes.push(PendingAttribute {
      name: qname,
      lexical: name.to_owned(),
      value: value.to_owned(),
      declares_namespace,
    });
    Ok(())
  }

  /// Ends the innermost open element.
  ///
  /// # Errors
  ///
  /// If the writer has already failed, that error. Otherwise a validity error if the element's attributes or its
  /// content leave it short of what the schema requires, or an error from the underlying writer.
  ///
  /// # Panics
  ///
  /// If no element is open.
  ///
  pub fn write_end_element(&mut self) -> Result<()> {
    self.guard()?;
    self.flush_pending()?;
    let name = self.open.pop().expect("write_end_element with no open element");
    let mut listener = FailFast::default();
    let _ = self.validator.end_element(name, &self.pool, &Location::unknown(), &mut listener);
    self.record(listener)?;
    self.inner.write_end_element()?;
    Ok(())
  }

  /// Writes character data, escaped.
  ///
  /// # Errors
  ///
  /// If the writer has already failed, that error. Otherwise a validity error if the schema allows no character data
  /// where this sits, or an error from the underlying writer.
  ///
  pub fn write_characters(&mut self, text: &str) -> Result<()> {
    self.guard()?;
    self.flush_pending()?;
    let whitespace_only = text.chars().all(chars::is_whitespace);
    let mut listener = FailFast::default();
    let _ = self.validator.characters(text, whitespace_only, &Location::unknown(), &mut listener);
    self.record(listener)?;
    self.inner.write_characters(text)?;
    Ok(())
  }

  /// Writes a CDATA section, splitting any `]]>` so it cannot close early.
  ///
  /// The validator receives the text as character data, since that is what a reader parses a CDATA section back into.
  ///
  /// # Errors
  ///
  /// As [`write_characters`](Self::write_characters).
  ///
  pub fn write_cdata(&mut self, text: &str) -> Result<()> {
    self.guard()?;
    self.flush_pending()?;
    let mut listener = FailFast::default();
    // Never whitespace-only: a CDATA section is significant character data, so an element-content model that admits
    // only whitespace must reject it even when every character in it is a space.
    let _ = self.validator.characters(text, false, &Location::unknown(), &mut listener);
    self.record(listener)?;
    self.inner.write_cdata(text)?;
    Ok(())
  }

  /// Writes a comment. It is not a validated event, so the validator never sees it.
  ///
  /// Like [`write_start_element`](Self::write_start_element), this call flushes the element opened before it, so a
  /// violation in that element is reported here.
  ///
  /// # Errors
  ///
  /// As [`write_start_element`](Self::write_start_element): the flush can report a violation in the element opened
  /// before this call, but the comment itself adds no event.
  ///
  pub fn write_comment(&mut self, text: &str) -> Result<()> {
    self.guard()?;
    self.flush_pending()?;
    self.inner.write_comment(text)?;
    Ok(())
  }

  /// Writes a processing instruction. It is not a validated event, so the validator never sees it.
  ///
  /// # Errors
  ///
  /// As [`write_comment`](Self::write_comment).
  ///
  pub fn write_processing_instruction(&mut self, target: &str, data: &str) -> Result<()> {
    self.guard()?;
    self.flush_pending()?;
    self.inner.write_processing_instruction(target, data)?;
    Ok(())
  }

  /// Returns the number of elements currently open, counting a start element still held back.
  ///
  #[must_use]
  pub fn depth(&self) -> usize {
    self.open.len() + usize::from(self.pending.is_some())
  }

  /// Runs the checks that need the whole document and returns the underlying writer.
  ///
  /// The caller has to end every element it opened first. This method does not check that the elements are balanced,
  /// and one left open leaves the output truncated.
  ///
  /// # Errors
  ///
  /// If the writer has already failed, that error. Otherwise a validity error from the last element still held back,
  /// or from a whole-document check such as an `IDREF` that matched no `ID` or a required element that never appeared,
  /// or an error from the underlying writer.
  ///
  pub fn finish(mut self) -> Result<W> {
    self.guard()?;
    self.flush_pending()?;
    let mut listener = FailFast::default();
    let _ = self.validator.finish(&mut listener);
    self.record(listener)?;
    Ok(self.inner.into_inner())
  }

  /// Checks the start element held back, if there is one, and emits it once the validator accepts it.
  ///
  /// The element and its attributes reach the underlying writer only after the check, so a refused element leaves
  /// nothing behind.
  ///
  fn flush_pending(&mut self) -> Result<()> {
    let Some(pending) = self.pending.take() else { return Ok(()) };
    let backing = PendingAttributes { attributes: &pending.attributes };
    let mut listener = FailFast::default();
    let _ = self.validator.start_element(
      pending.name,
      Attributes::new(&backing),
      &self.pool,
      &Location::unknown(),
      &mut listener,
    );
    self.record(listener)?;
    self.inner.write_start_element(&pending.lexical)?;
    for attribute in &pending.attributes {
      self.inner.write_attribute(&attribute.lexical, &attribute.value)?;
    }
    self.open.push(pending.name);
    Ok(())
  }

  /// Interns a written name into this writer's pool as a [`QName`] carrying its lexical prefix and local part.
  ///
  /// The namespace URI is left unset, because nothing here resolves a declaration to a URI.
  ///
  fn intern(&mut self, name: &str) -> QName {
    match name.split_once(':') {
      Some((prefix, local)) => {
        let prefix = self.pool.intern(prefix);
        let local = self.pool.intern(local);
        QName::new(Some(prefix), None, local)
      }
      None => QName::new(None, None, self.pool.intern(name)),
    }
  }

  /// Returns the error that failed this writer, if a write has already been refused.
  ///
  fn guard(&self) -> Result<()> {
    match &self.failure {
      Some(error) => Err(error.to_error()),
      None => Ok(()),
    }
  }

  /// Records the error a check reported, if it reported one, marking this writer failed and returning that error.
  ///
  fn record(&mut self, listener: FailFast) -> Result<()> {
    if let Some(error) = listener.first() {
      self.failure = Some(error.clone());
      return Err(error.to_error());
    }
    Ok(())
  }
}

// Written by hand because a `Box<dyn Validator>` is not `Debug`. It shows what a caller can act on and nothing else.
impl<W> std::fmt::Debug for ValidatingWriter<W> {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let depth = self.open.len() + usize::from(self.pending.is_some());
    f.debug_struct("ValidatingWriter")
      .field("depth", &depth)
      .field("failed", &self.failure.is_some())
      .finish_non_exhaustive()
  }
}

#[cfg(test)]
mod tests {
  use std::ops::ControlFlow;

  use xenolith_core::error::Error;

  use super::*;

  /// A schema that allows only the element names given to it, resolving each name to a string through the pool it is
  /// lent.
  struct AllowedElements {
    allowed: Vec<String>,
  }

  impl Validator for AllowedElements {
    fn start_element(
      &mut self,
      name: QName,
      _attributes: Attributes<'_>,
      pool: &NamePool,
      at: &Location,
      errors: &mut dyn xenolith_validate::ErrorListener,
    ) -> ControlFlow<()> {
      let local = pool.resolve(name.local());
      if self.allowed.iter().any(|a| a == local) {
        ControlFlow::Continue(())
      } else {
        errors.report(ValidityError::new(format!("element \"{local}\" is not allowed"), at.clone()))
      }
    }

    fn characters(
      &mut self,
      _text: &str,
      _ws: bool,
      _at: &Location,
      _errors: &mut dyn xenolith_validate::ErrorListener,
    ) -> ControlFlow<()> {
      ControlFlow::Continue(())
    }

    fn end_element(
      &mut self,
      _name: QName,
      _pool: &NamePool,
      _at: &Location,
      _errors: &mut dyn xenolith_validate::ErrorListener,
    ) -> ControlFlow<()> {
      ControlFlow::Continue(())
    }

    fn finish(&mut self, _errors: &mut dyn xenolith_validate::ErrorListener) -> ControlFlow<()> {
      ControlFlow::Continue(())
    }
  }

  fn allowing(names: &[&str]) -> Box<dyn Validator> {
    Box::new(AllowedElements { allowed: names.iter().map(|s| (*s).to_owned()).collect() })
  }

  #[test]
  fn a_conforming_document_is_written() {
    let mut w = ValidatingWriter::new(Vec::new(), allowing(&["a", "b"]));
    w.write_start_element("a").unwrap();
    w.write_attribute("x", "1").unwrap();
    w.write_start_element("b").unwrap();
    w.write_end_element().unwrap();
    w.write_end_element().unwrap();
    let out = String::from_utf8(w.finish().unwrap()).unwrap();
    assert_eq!(out, "<a x=\"1\"><b/></a>");
  }

  #[test]
  fn a_disallowed_element_is_refused_at_finish() {
    let mut w = ValidatingWriter::new(Vec::new(), allowing(&["a"]));
    w.write_start_element("bad").unwrap(); // held back, not yet checked
    let error = w.finish().unwrap_err(); // flushing it is what checks it
    assert!(matches!(error, Error::Validity { .. }), "{error}");
    assert!(error.to_string().contains("bad"));
  }

  #[test]
  fn a_refusal_poisons_later_writes() {
    let mut w = ValidatingWriter::new(Vec::new(), allowing(&["a"]));
    w.write_start_element("a").unwrap();
    w.write_start_element("bad").unwrap(); // `a` is flushed and allowed, and `bad` is now held back
    let error = w.write_end_element().unwrap_err(); // flushing `bad` is refused
    assert!(matches!(error, Error::Validity { .. }), "{error}");
    // The writer has failed, so a later write returns the same error rather than emitting more.
    assert!(w.write_characters("x").is_err());
  }
}
